/** Centralized path resolution for output files */
import { OUTPUT_DIR, ARTICLES_DIR } from "../constants.js";

export const paths = {
  output: OUTPUT_DIR,
  articles: ARTICLES_DIR,
  toc: `${OUTPUT_DIR}/toc.json`,
  manifest: `${OUTPUT_DIR}/manifest.json`,
  verificationReport: `${OUTPUT_DIR}/verification-report.json`,
  monitorReport: `${OUTPUT_DIR}/monitor-report.json`,
  consolidatedJson: `${OUTPUT_DIR}/crescent-city-code.json`,
  plainText: `${OUTPUT_DIR}/crescent-city-code.txt`,
  sectionIndex: `${OUTPUT_DIR}/section-index.csv`,
  markdown: `${OUTPUT_DIR}/markdown`,
  state: `${OUTPUT_DIR}/state`,
  news: `${OUTPUT_DIR}/news`,
  newsSeenIds: `${OUTPUT_DIR}/state/news-seen-ids.json`,
  newsHealth: `${OUTPUT_DIR}/news/source-health.json`,
  govMeetings: `${OUTPUT_DIR}/gov_meetings`,
  govMeetingsHealth: `${OUTPUT_DIR}/gov_meetings/source-health.json`,
  youtube: `${OUTPUT_DIR}/youtube`,
  youtubeHealth: `${OUTPUT_DIR}/youtube/source-health.json`,
  triplicate: `${OUTPUT_DIR}/triplicate`,
  triplicateHealth: `${OUTPUT_DIR}/triplicate/source-health.json`,
  alertsHealth: `${OUTPUT_DIR}/alerts/source-health.json`,
  curated: `${OUTPUT_DIR}/curated`,
  curationSeen: `${OUTPUT_DIR}/state/curation-seen.json`,
  reports: `${OUTPUT_DIR}/reports`,
  indexManifest: `${OUTPUT_DIR}/state/index-manifest.json`,
  article: (guid: string) => `${ARTICLES_DIR}/${guid}.json`,
};
